### PR TITLE
Authentication via token

### PR DESCRIPTION
**Pull request by thousandsofthem**
* Added ability to do auth via token instead of user/pass
* Added README section with auth examples

### CODE REVIEW

**Comment by mmmries** [comment]
❤️ 💙 💚 💛 ❤️ 💙 💚 💛 ❤️ 💙 💚 💛 ❤️ 💙 💚 💛 
@thousandsofthem thank you so much for contributing to the project
 ❤️ 💙 💚 💛 ❤️ 💙 💚 💛 ❤️ 💙 💚 💛 ❤️ 💙 💚 💛 

I'm wondering if we should add an end-to-end test that just verifies that we can login via token. Something along the lines of the `gnat_test.exs` file's "connect to a server with authentication" test? I haven't setup token authentication before so I'm not sure how hard that is. Have you tested this against a live server?

**Comment by thousandsofthem** [comment]
Yes, this code connects to live server via token auth just fine

**Comment by mmmries** [comment]
Sounds good, I'll try adding in a test really quickly within the master branch and then get this released on hex.pm. Thanks again!

**Comment by mmmries** [comment]
This has been released as `0.7.0` on hex.pm. Thanks again for your work on this

**Comment by thousandsofthem** [comment]
👍

**Pull request merged**
